config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "static_pages/home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :microposts, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom
navbar-inverse footer">
  <ul><%= link_to t("static_pages.home.help"), "#" %></ul>
  <ul><%= link_to t("static_pages.home.about"), "#" %></ul>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top
navbar-inverse">
<div class="container">
  <%= link_to "sample app", "#", id: "logo" %>
  <nav>
   <ul class="nav navbar-nav navbar-right">
    <%= link_to t("en"), locale: :en %>
    <%= link_to t("vi"), locale: :vi %>
    <li><%= link_to t(".title"), root_url %></li>
    <li><%= link_to t(".help"), "#" %></li>
    <li><%= link_to t(".about"), "#" %></li>
    <% if logged_in? %>
    <li><%= link_to t(".user"), users_path %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= t(".account") %><b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to t(".profile"), current_user %></li>
        <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
          <%= link_to t(".log_out"), logout_path, method: :delete %>
        </li>
      </ul>
    </li>
    <% else %>
    <li><%= link_to t(".log_in"), login_path %></li>
    <% end %>
  </ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
   <%= render "layouts/header" %>
   <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
   </div>
  </body>
</html>